vich_uploader:
    db_driver: orm

    mappings:
        plat_image:
            uri_prefix: /build/images/plat
            upload_destination: '%kernel.project_dir%/public/upload_images/plat'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        
        staff_image:
            uri_prefix: /build/images/staff
            upload_destination: '%kernel.project_dir%/public/upload_images/staff'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
